---
- name: Deploy Application
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: /var/lib/jenkins/workspace/app-cicd-pipeline/webapp/target/webapp.war
        dest: /var/lib/tomcat/webapps
        owner: ansadmin
        group: ansadmin
        mode: '0644'
      when: inventory_hostname in groups[environment]
