---
- name: Ansible Copy Local to Remote
  hosts: dev_server:stage_server:prod_server
  become: false
  vars:
    src_path: "/var/lib/jenkins/workspace/app-cicd-pipeline/webapp/target/webapp.war"
    dest_path: "/var/lib/tomcat/webapps"
  tasks:
    - name: Copy file using SCP
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}/webapp.war"
        mode: push
      become_user: ansadmin
      become: true
      become_method: sudo
      # Optional: Set ownership and permissions
      # file:
      #   path: "{{ dest_path }}/webapp.war"
      #   owner: ansadmin
      #   group: ansadmin
      #   mode: '0644'
tasks:
  - name: Show source file details
    debug:
      msg: "Source file attributes: {{ lookup('file', src_path) }}"

  - name: Copy file using SCP
    ansible.builtin.synchronize:
      src: "{{ src_path }}"
      dest: "{{ dest_path }}/webapp.war"
      mode: push
    become_user: ansadmin
    become: true
    become_method: sudo

  - name: Show destination file details
    debug:
      msg: "Destination file attributes: {{ lookup('file', dest_path + '/webapp.war') }}"
