---
- name: Deploy to Environments
  hosts: dev_server:stage_server:prod_server  # Run the playbook on all environments
  become: true

  tasks:
    - name: Ansible Copy Local to Remote
      ansible.builtin.shell: cp /var/lib/jenkins/workspace/app-cicd-pipeline/webapp/target/webapp.war /var/lib/tomcat/webapps/webapp.war
#        src: "/var/lib/jenkins/workspace/app-cicd-pipeline/webapp/target/webapp.war"
#        dest: "/var/lib/tomcat/webapps/webapp.war"
        owner: ansadmin
        group: ansadmin
        mode: "0644"
      register: copy_result
    - name: Debug Copy Result
      debug:
        var: copy_result

#- name: Ansible Copy Local to Remote
#  hosts: "{{hosts}}"
#  vars:
#    src_path: "{{ workspace_path }}/webapp/target/webapp.war"
#    dest_path: "/var/lib/tomcat/webapps"
#    config_file_src_path: "{{ hosts }}-config.yaml"
#    config_file_dest_path: "/home"
#  tasks:
#    - name: copying file with playbook
#      become: true
#      copy:
#        src: "{{ src_path }}"
#        dest: "{{ dest_path }}"
#        owner: ansadmin
#        group: ansadmin
#        mode: 0644
