---
- name: Deploy to Environments
  hosts: all
  become: true

  tasks:
    - name: Ansible Copy Local to Remote
      hosts: "{{ hosts }}"
      copy:
        src: "{{ workspace_path }}/webapp/target/webapp.war"
        dest: "/var/lib/tomcat/webapps/webapp.war"
        owner: ansadmin
        group: ansadmin
        mode: "0644"
        

#- name: Ansible Copy Local to Remote
#  hosts: "{{hosts}}"
#  vars:
#    src_path: "{{ workspace_path }}/webapp/target/webapp.war"
#    dest_path: "/var/lib/tomcat/webapps"
#    config_file_src_path: "{{ hosts }}-config.yaml"
#    config_file_dest_path: "/home"
#  tasks:
#    - name: copying file with playbook
#      become: true
#      copy:
#        src: "{{ src_path }}"
#        dest: "{{ dest_path }}"
#        owner: ansadmin
#        group: ansadmin
#        mode: 0644
